# fly.toml file generated for chatvolt on 2023-04-05T19:24:27+02:00

app = "chatvolt"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "fra"


[processes]
web = "node apps/dashboard/server.js"
# https://nodejs.org/api/cli.html#--max-old-space-sizesize-in-megabytes
worker = "node --max-old-space-size=1536 apps/dashboard/.next/server/datasource-loader.js"
# cron = "supercronic crontab"

[build]
  [build.args]
    NEXT_PUBLIC_S3_BUCKET_NAME = ""
    NEXT_PUBLIC_AWS_ENDPOINT = ""
    NEXT_PUBLIC_DASHBOARD_URL = ""
    NEXT_PUBLIC_SLACK_CLIENT_ID=""
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=""
    NEXT_PUBLIC_STRIPE_PAYMENT_LINK_LEVEL_1=""
    NEXT_PUBLIC_STRIPE_PRICING_TABLE_ID=""
    NEXT_PUBLIC_CRISP_PLUGIN_ID=""
    NEXT_PUBLIC_GA_ID=""
    NEXT_PUBLIC_HOTJAR_ID=""
    NEXT_PUBLIC_FATHOM_SITE_ID=""
    NEXT_PUBLIC_POSTHOG_KEY=""
    NEXT_PUBLIC_POSTHOG_HOST=""
    NEXT_PUBLIC_MIXPANEL_TOKEN=""
    NEXT_PUBLIC_FACEBOOK_PIXEL_ID=""


[http_service]
  processes = ["web"]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  [http_service.concurrency]
    type = "connections"
    hard_limit = 550
    soft_limit = 500

[[services]]
  internal_port = 8080
  processes = ["worker"]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running=6
  [[services.ports]]
    handlers = ["http"]
    port = 80
    # force_https = true  # optional

# [[services]]
#   # processes = ["app"]
#   processes = ["web"]
#   protocol = "tcp"
#   internal_port = 3000

#   [[services.ports]]
#     port = 80
#     handlers = ["http"]
#     force_https = true

#   [[services.ports]]
#     port = 443
#     handlers = ["tls", "http"]
#   [services.concurrency]
#     type = "connections"
#     hard_limit = 25
#     soft_limit = 20
